TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization

Documentation/LocalizedContent/Index.rst
Hi, I'm at the bootup day and looked for something to edit.
=> Fixed some typos

Documentation/TyposcriptConfiguration/Index.rst
This is just a small notice to mark this section as obsolete.
=> Notice about outdated information

Documentation/Includes.txt, Documentation/Index.rst, Documentation/Settings.cfg
- Add review status information to be displayed on every page
- Fix formatting issues on start page
=> Maintenance update

Documentation/Includes.txt, Documentation/Index.rst, Documentation/Settings.cfg
- Add review status information to be displayed on every page
- Fix formatting issues on start page
=> Maintenance update (7.6)

Documentation/Includes.txt, Documentation/Index.rst, Documentation/Settings.cfg
- Add review status information to be displayed on every page
- Fix formatting issues on start page
=> Maintenance update (8.7)

Documentation/Includes.txt, Documentation/Index.rst, Documentation/Settings.cfg
- Add review status information to be displayed on every page
- Fix formatting issues on start page
=> Maintenance update (9.5)

Documentation/CoreSupport/Tca/Index.rst
See Deprecation 88746
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/849
=> [TASK] Correct reference to PageRepository

Documentation/CoreSupport/Tca/Index.rst
See Important 89672
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/845
=> [TASK] Add warning about exclusion of transOrigPointerField

.editorconfig, Documentation/Settings.cfg
intersphinx_mapping, github_branch etc
=> Change settings from master to main

Documentation/CoreSupport/Tca/Index.rst, Documentation/LanguageMenu/Index.rst, Documentation/LocalizationOverview/Index.rst, Documentation/LocalizedContent/Index.rst, Documentation/LocalizedLabels/Index.rst
to make it more clear where code should go
Releases: main, 11.5
=> [TASK] Add captions to code-blocks (#94)

Documentation/SettingUpLanguages/Index.rst
=> add note about changes

Documentation/LocalizedLabels/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/495
Releases: main, 12.4
=> [TASK] #101003 - Remove deprecated AbstractPlugin

Documentation/CharacterSets/Index.rst
- Adjust wordings
- Update link to MySQL documentation
- Add links to MariaDB and PostgreSQL documentation
Releases: main, 12.4
=> [TASK] Revise character sets chapter

Documentation/CoreSupport/Index.rst, Documentation/CoreSupport/Permissions/Index.rst, Documentation/CoreSupport/Tca/Index.rst
- Adjust wordings
- Add links to other sections/manuals
- Fix reference to migration of new language TCA type
- Fix transOrigPointerField example
Releases: main, 12.4, 11.5
=> [TASK] Revise core support chapter

Documentation/CoreSupport/Index.rst, Documentation/CoreSupport/Permissions/Index.rst, Documentation/CoreSupport/Tca/Index.rst
- Adjust wordings
- Add links to other sections/manuals
- Fix reference to migration of new language TCA type
- Fix transOrigPointerField example
Releases: main, 12.4, 11.5
=> [Backport 11.5] [TASK] Revise core support chapter (#79)

Documentation/CoreSupport/Tca/Index.rst
=> [TASK] Remove superfluous quotation mark

Documentation/LocalizedContent/Index.rst
Releases: main, 12.4, 11.5
---------
=> [TASK] Revise localized content chapter (#93)

Documentation/Settings.cfg
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/734
Releases: main
=> [TASK] #102440 - Merge EXT:t3editor into backend

Documentation/guides.xml
=> [BUGFIX] Correct the interlink shortcode

Documentation/Includes.rst.txt
=> [TASK] Add end of life hint & remove unused content from Includes.rst.txt
